# -*- coding: utf-8 -*-
"""Copy of plant_disease_recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xjfm1nBx_q0swAi3NGO_lR0R10O8KpMp
"""

!wget -O "dataset.zip" "https://data.mendeley.com/public-files/datasets/tywbtsjrjv/files/b4e3a32f-c0bd-4060-81e9-6144231f2520/file_downloaded"



!unzip /content/dataset.zip

import os

path="/content/Plant_leave_diseases_dataset_with_augmentation"
ex=("jpg","jpeg","png")
total=0
for cls in sorted(os.listdir(path)):
    p=os.path.join(path,cls)
    if os.path.isdir(p):
        c=len([f for f in os.listdir(p) if f.lower().endswith(ex)])
        total+=c
        print(cls,":",c)
print("Total images =",total)

import matplotlib.pyplot as plt
import numpy as np
import os
import tensorflow as tf

!pip install split-folders



import splitfolders
splitfolders.ratio("/content/Plant_leave_diseases_dataset_with_augmentation", output="dataset", seed=1337, ratio=(.8, .1,.1))

import os

path="/content/dataset/train"
ex=("jpg","jpeg","png")
total=0
for cls in sorted(os.listdir(path)):
    p=os.path.join(path,cls)
    if os.path.isdir(p):
        c=len([f for f in os.listdir(p) if f.lower().endswith(ex)])
        total+=c
        print(cls,":",c)
print("Total images =",total)

import os

path="/content/dataset/test"
ex=("jpg","jpeg","png")
total=0
for cls in sorted(os.listdir(path)):
    p=os.path.join(path,cls)
    if os.path.isdir(p):
        c=len([f for f in os.listdir(p) if f.lower().endswith(ex)])
        total+=c
        print(cls,":",c)
print("Total images =",total)

import os

path="/content/dataset/val"
ex=("jpg","jpeg","png")
total=0
for cls in sorted(os.listdir(path)):
    p=os.path.join(path,cls)
    if os.path.isdir(p):
        c=len([f for f in os.listdir(p) if f.lower().endswith(ex)])
        total+=c
        print(cls,":",c)
print("Total images =",total)

"""**DATA** **PREPROCESSING**"""

train_dir = "/content/dataset/train"
validation_dir = "/content/dataset/val"

BATCH_SIZE = 32
IMG_SIZE = (160, 160)

train_dataset = tf.keras.utils.image_dataset_from_directory(train_dir,
                                                            shuffle=True,
                                                            batch_size=BATCH_SIZE,
                                                            image_size=IMG_SIZE)

validation_dataset = tf.keras.utils.image_dataset_from_directory(validation_dir,
                                                                 shuffle=True,
                                                                 batch_size=BATCH_SIZE,
                                                                 image_size=IMG_SIZE)
test_dir="/content/dataset/test"
test_dataset = tf.keras.utils.image_dataset_from_directory(test_dir,
                                                                 batch_size=BATCH_SIZE,
                                                                 image_size=IMG_SIZE)

class_names = train_dataset.class_names

plt.figure(figsize=(10, 10))
for images, labels in train_dataset.take(1):
  for i in range(9):
    ax = plt.subplot(3, 3, i + 1)
    plt.imshow(images[i].numpy().astype("uint8"))
    plt.title(class_names[labels[i]])
    plt.axis("off")

class_names

AUTOTUNE = tf.data.AUTOTUNE

train_dataset = train_dataset.prefetch(buffer_size=AUTOTUNE)
validation_dataset = validation_dataset.prefetch(buffer_size=AUTOTUNE)
test_dataset = test_dataset.prefetch(buffer_size=AUTOTUNE)

preprocess_input =tf.keras.applications.efficientnet.preprocess_input

"""**Create the base model from the pre-trained convnets**"""

IMG_SHAPE = IMG_SIZE + (3,)
base_model=tf.keras.applications.EfficientNetB4(input_shape=IMG_SHAPE,
  include_top=False,
    weights='imagenet',
)

image_batch, label_batch = next(iter(train_dataset))
feature_batch = base_model(image_batch)
print(feature_batch.shape)

"""Feature extraction"""

base_model.trainable = False

# Let's take a look at the base model architecture
base_model.summary()

global_average_layer = tf.keras.layers.GlobalAveragePooling2D()
feature_batch_average = global_average_layer(feature_batch)
print(feature_batch_average.shape)

prediction_layer = tf.keras.layers.Dense(len(class_names), activation='sigmoid')
prediction_batch = prediction_layer(feature_batch_average)
print(prediction_batch.shape)

inputs = tf.keras.Input(shape=(160, 160, 3))
x = preprocess_input(inputs)
x = base_model(x, training=False)
x = global_average_layer(x)
x = tf.keras.layers.Dropout(0.2)(x)
outputs = prediction_layer(x)
model = tf.keras.Model(inputs, outputs)

model.summary()

len(model.trainable_variables)

tf.keras.utils.plot_model(model, show_shapes=True)

"""**Compile the model**"""

model.compile(optimizer=tf.keras.optimizers.Adam(),
              loss=tf.keras.losses.SparseCategoricalCrossentropy(),
              metrics=[tf.keras.metrics.SparseCategoricalAccuracy(name='accuracy')])

"""**Train the model**"""

initial_epochs = 6

loss0, accuracy0 = model.evaluate(validation_dataset)

import os

val_dir = "/content/splitted/val"  # or whatever your val path is
bad_files = []

for root, dirs, files in os.walk(val_dir):
    for name in files:
        path = os.path.join(root, name)
        try:
            if os.path.getsize(path) == 0:
                bad_files.append(path)
        except:
            bad_files.append(path)

print("Bad files:")
for f in bad_files:
    print(f)



print("initial loss: {:.2f}".format(loss0))
print("initial accuracy: {:.2f}".format(accuracy0))

history = model.fit(train_dataset,
                    epochs=initial_epochs,
                    validation_data=validation_dataset)

acc = history.history['accuracy']
val_acc = history.history['val_accuracy']

loss = history.history['loss']
val_loss = history.history['val_loss']

plt.figure(figsize=(8, 8))
plt.subplot(2, 1, 1)
plt.plot(acc, label='Training Accuracy')
plt.plot(val_acc, label='Validation Accuracy')
plt.legend(loc='lower right')
plt.ylabel('Accuracy')
plt.ylim([min(plt.ylim()),1])
plt.title('Training and Validation Accuracy')

plt.subplot(2, 1, 2)
plt.plot(loss, label='Training Loss')
plt.plot(val_loss, label='Validation Loss')
plt.legend(loc='upper right')
plt.ylabel('Cross Entropy')
plt.ylim([0,1.0])
plt.title('Training and Validation Loss')
plt.xlabel('epoch')
plt.show()

"""**Fine Tuning**"""

base_model.trainable = True

# Let's take a look to see how many layers are in the base model
print("Number of layers in the base model: ", len(base_model.layers))

# Fine-tune from this layer onwards
fine_tune_at = 100

# Freeze all the layers before the `fine_tune_at` layer
for layer in base_model.layers[:fine_tune_at]:
  layer.trainable = False

"""**Compile the model**


"""

model.compile(optimizer=tf.keras.optimizers.Adam(),
              loss=tf.keras.losses.SparseCategoricalCrossentropy(),
              metrics=[tf.keras.metrics.SparseCategoricalAccuracy(name='accuracy')])

model.summary()

len(model.trainable_variables)

fine_tune_epochs = 10
total_epochs =  initial_epochs + fine_tune_epochs

history_fine = model.fit(train_dataset,
                         epochs=total_epochs,
                         initial_epoch=len(history.epoch),
                         validation_data=validation_dataset)

acc += history_fine.history['accuracy']
val_acc += history_fine.history['val_accuracy']

loss += history_fine.history['loss']
val_loss += history_fine.history['val_loss']

plt.figure(figsize=(8, 8))
plt.subplot(2, 1, 1)
plt.plot(acc, label='Training Accuracy')
plt.plot(val_acc, label='Validation Accuracy')
plt.ylim([0.8, 1])
plt.plot([initial_epochs-1,initial_epochs-1],
          plt.ylim(), label='Start Fine Tuning')
plt.legend(loc='lower right')
plt.title('Training and Validation Accuracy')

plt.subplot(2, 1, 2)
plt.plot(loss, label='Training Loss')
plt.plot(val_loss, label='Validation Loss')
plt.ylim([0, 1.0])
plt.plot([initial_epochs-1,initial_epochs-1],
         plt.ylim(), label='Start Fine Tuning')
plt.legend(loc='upper right')
plt.title('Training and Validation Loss')
plt.xlabel('epoch')
plt.show()

loss, accuracy = model.evaluate(test_dataset)
print('Test accuracy :', accuracy)

# Retrieve a batch of images from the test set
image_batch, label_batch = test_dataset.as_numpy_iterator().next()
predictions = model.predict_on_batch(image_batch)
predictions = tf.argmax(predictions,axis=1)

print('Predictions:\n', predictions.numpy())
print('Labels:\n', label_batch)

plt.figure(figsize=(10, 10))
for i in range(9):
  ax = plt.subplot(3, 3, i + 1)
  plt.imshow(image_batch[i].astype("uint8"))
  plt.title(class_names[predictions[i]])
  plt.axis("off")



import tensorflow as tf
import splitfolders
import os
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# ---------------------------------------------------------
# STEP 1: PREPARE FOLDERS (Fixing the order)
# ---------------------------------------------------------
# We check if the dataset exists to avoid errors
if not os.path.exists("/content/dataset"):
    print("Splitting data... this might take a moment.")
    splitfolders.ratio(
        "/content/Plant_leave_diseases_dataset_with_augmentation",
        output="dataset",
        seed=1337,
        ratio=(.8, .1, .1)
    )
else:
    print("Data folders already exist. Skipping split.")

# ---------------------------------------------------------
# STEP 2: DEFINE THE TEST DATASET (Fixing the NameError)
# ---------------------------------------------------------
BATCH_SIZE = 32
IMG_SIZE = (160, 160)
test_dir = "/content/dataset/test"

print("Loading test_dataset...")
test_dataset = tf.keras.utils.image_dataset_from_directory(
    test_dir,
    shuffle=True,  # Default setting
    batch_size=BATCH_SIZE,
    image_size=IMG_SIZE
)

# ---------------------------------------------------------
# STEP 3: CALCULATE METRICS
# ---------------------------------------------------------
y_true = []
y_pred = []

print("Running predictions...")
# Iterate batch by batch to ensure images and labels match
for images, labels in test_dataset:
    # Get True Labels
    y_true.extend(labels.numpy())

    # Get Predictions
    batch_predictions = model.predict(images, verbose=0)
    y_pred.extend(np.argmax(batch_predictions, axis=1))

# Calculate Scores
acc = accuracy_score(y_true, y_pred)
prec = precision_score(y_true, y_pred, average='macro')
rec = recall_score(y_true, y_pred, average='macro')
f1 = f1_score(y_true, y_pred, average='macro')

print("\n" + "="*30)
print(f"Accuracy:  {acc:.4f} ({acc*100:.2f}%)")
print(f"Precision: {prec:.4f}")
print(f"Recall:    {rec:.4f}")
print(f"F-Measure: {f1:.4f}")
print("="*30)

import tensorflow as tf
import splitfolders
import os
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

if not os.path.exists("/content/dataset"):
    print("Splitting data... this might take a moment.")
    splitfolders.ratio(
        "/content/Plant_leave_diseases_dataset_with_augmentation",
        output="dataset",
        seed=1337,
        ratio=(.8, .1, .1)
    )
else:
    print("Data folders already exist. Skipping split.")

BATCH_SIZE=32
IMG_SIZE=(160,160)
test_dir="/content/dataset/test"

print("Loading test_dataset...")
test_dataset=tf.keras.utils.image_dataset_from_directory(
    test_dir,
    shuffle=True,
    batch_size=BATCH_SIZE,
    image_size=IMG_SIZE
)

class_names=test_dataset.class_names

y_true=[]
y_pred=[]

print("Running predictions...")
for images,labels in test_dataset:
    y_true.extend(labels.numpy())
    batch_predictions=model.predict(images,verbose=0)
    y_pred.extend(np.argmax(batch_predictions,axis=1))

y_true=np.array(y_true)
y_pred=np.array(y_pred)

acc=accuracy_score(y_true,y_pred)
prec=precision_score(y_true,y_pred,average='macro')
rec=recall_score(y_true,y_pred,average='macro')
f1=f1_score(y_true,y_pred,average='macro')

print("\n"+"="*30)
print(f"Accuracy:  {acc:.4f} ({acc*100:.2f}%)")
print(f"Precision: {prec:.4f}")
print(f"Recall:    {rec:.4f}")
print(f"F-Measure: {f1:.4f}")
print("="*30)

cm=confusion_matrix(y_true,y_pred,labels=range(len(class_names)))

max_name_len=max(len(name) for name in class_names)
col_width=max(max_name_len,5)+2

header="".ljust(col_width)+"".join(name.ljust(col_width) for name in class_names)
print("\nConfusion Matrix (rows=true, cols=pred):")
print(header)
for i,row in enumerate(cm):
    row_str="".join(f"{v:{col_width}d}" for v in row)
    print(class_names[i].ljust(col_width)+row_str)

from google.colab import drive
drive.mount('/content/drive')

model.save('/content/drive/MyDrive/plant_model.keras')

from tensorflow.keras.models import load_model
model = load_model('/content/drive/MyDrive/plant_model.keras')

print("Loading test_dataset...")
test_dataset=tf.keras.utils.image_dataset_from_directory(
    test_dir,
    shuffle=True,
    batch_size=BATCH_SIZE,
    image_size=IMG_SIZE
)

class_names=test_dataset.class_names

y_true=[]
y_pred=[]

print("Running predictions...")
for images,labels in test_dataset:
    y_true.extend(labels.numpy())
    batch_predictions=model.predict(images,verbose=0)
    y_pred.extend(np.argmax(batch_predictions,axis=1))

y_true=np.array(y_true)
y_pred=np.array(y_pred)

from sklearn.metrics import confusion_matrix

cm=confusion_matrix(y_true,y_pred,labels=range(len(class_names)))

import pandas as pd
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_true, y_pred)

cm_df = pd.DataFrame(
    cm,
    index=class_names,
    columns=class_names
)

cm_df

total_cost = actual_cost_df.values.sum()
print("Total Classification Cost:", total_cost)

